#!/usr/bin/env bash

# FILE:   merge pdf files -- 
# AUTHOR: Adrian Wyssmann <aedu@wyssmann.com
# DATE:   17 Dec 2011
#
# Copyright (C) 2011 Adrian Wyssmann <aedu@wyssmann.com>
# All rights reserved.


