#!/bin/bash

# FILE:   merge pdf files -- 
# AUTHOR: Adrian Wyssmann <aedu@wyssmann.com
# DATE:   17 Dec 2011
#
# Copyright (C) 2011 Adrian Wyssmann <aedu@wyssmann.com>
# All rights reserved.

# https://stackoverflow.com/questions/7503780/how-to-convert-pdf-to-low-resolution-but-good-quality-jpeg
# -dDOINTERPOLATE

# https://stackoverflow.com/questions/8158584/ghostscript-to-merge-pdfs-compresses-the-result
# -dPDFSETTINGS=/prepress
# http://milan.kupcevic.net/ghostscript-ps-pdf/#refs

counter=1

title="Merge PDFs"
scale="Choose which resolution"
temp_file="temp.pdf"
merged_file="merged.pdf"
pdf_file=$1

#resolution=`gdialog --title "$title" --checklist "$scale" 200 100 6 100 " " off 200 " " off 300 " " off 600 " " off 1200 " " off 2>&1`
(
let step=100/$#
percentage=0

while [ $# -gt 0 ]; do
	pdf_file=$1	
	if [ $counter -eq 1 ]
	then
		echo "# Copy ${pdf_file} ${temp_file}"
		cp ${pdf_file} ${temp_file}
	else
		echo "# Merge ${pdf_file}"
		gs  -dPDFSETTINGS=/prepress  -dUseCIEColor=true  -dNOPAUSE -sDEVICE=pdfwrite -r300 -sOUTPUTFILE=$merged_file -dBATCH $temp_file $pdf_file
		mv ${merged_file} ${temp_file}
	fi
	let percentage=$counter*$step
	counter=`expr $counter + 1`
	echo $percentage
	shift
done

) | zenity --progress \
  --title="Merging Files" \
  --text="Merging files..." \
  --percentage=0 \
  --auto-close

if [ "$?" = -1 ] ; then
		zenity --error \
		  --text="Merging canceled."
fi
echo "mv $temp_file $pdf_file.new"
mv $temp_file $pdf_file".new"
